
listAllToons = [
    'MAGMATROOPER', 'HERMITYODA','GREEFKARGA',
    'ZEBS3','BARRISSOFFEE','CT210408','B1BATTLEDROIDV2','COLONELSTARCK','BB8','POGGLETHELESSER',
    'FIRSTORDERSPECIALFORCESPILOT','GENERALKENOBI','JAWASCAVENGER','L3_37','DROIDEKA','EWOKSCOUT','K2SO','NIGHTSISTERACOLYTE',
    'SITHTROOPER','IG86SENTINELDROID','SITHMARAUDER','C3POCHEWBACCA','REYJEDITRAINING','KYLOREN','DENGAR','MAGNAGUARD',
    'QUIGONJINN','ROYALGUARD','BASTILASHAN','GEONOSIANSPY','JAWA','QIRA','POE','TALIA','NIGHTSISTERZOMBIE','GRANDADMIRALTHRAWN',
    'SCARIFREBEL','IMPERIALPROBEDROID','SABINEWRENS3','YOUNGHAN','PAPLOO','EWOKELDER','EPIXPOE','CHIEFCHIRPA',
    'GENERALHUX','CT5555','VISASMARR','LUKESKYWALKER','ADMINISTRATORLANDO','ANAKINKNIGHT','ADMIRALPIETT','GENERALSKYWALKER',
    'NIGHTSISTERSPIRIT','CLONESERGEANTPHASEI','SUPREMELEADERKYLOREN','ADMIRALACKBAR','STORMTROOPER','LUMINARAUNDULI',
    'JANGOFETT','HOTHREBELSCOUT','NUTEGUNRAY','VEERS','PAO','IG88','REY','DARTHNIHILUS','EMPERORPALPATINE','MONMOTHMA',
    'HOTHHAN','PLOKOON','DAKA','GRANDMOFFTARKIN','LOGRAY','GEONOSIANSOLDIER','CARADUNE','HK47','TUSKENRAIDER',
    'CASSIANANDOR','DARTHTRAYA','BAZEMALBUS','EPIXFINN','ZAALBAR','CLONEWARSCHEWBACCA','COMMANDERLUKESKYWALKER',
    'B2SUPERBATTLEDROID','DARTHSIDIOUS','OLDBENKENOBI','KYLORENUNMASKED','YOUNGCHEWBACCA','YOUNGLANDO','HANSOLO',
    'ARMORER','SMUGGLERHAN','THEMANDALORIAN','UGNAUGHT','FOSITHTROOPER','SMUGGLERCHEWBACCA','DARTHREVAN',
    'R2D2_LEGENDARY','HUMANTHUG','THEMANDALORIANBESKARARMOR','GARSAXON',    'CORUSCANTUNDERWORLDPOLICE','ENFYSNEST',
    'MOTHERTALZIN','BIGGSDARKLIGHTER','CC2224','C3POLEGENDARY','JEDIKNIGHTREVAN','PADMEAMIDALA',
    'NIGHTSISTERINITIATE','CT7567','MOFFGIDEONS1','ZAMWESELL','SUNFAC','LOBOT','EMBO','IMAGUNDI','EETHKOTH','T3_M4',
    'HOTHREBELSOLDIER',    'ASAJVENTRESS','GRIEVOUS','CHIRRUTIMWE','JUHANI','KANANJARRUSS3','ROSETICO',
    'JEDIKNIGHTCONSULAR','AHSOKATANO','DIRECTORKRENNIC',    'STORMTROOPERHAN','HERASYNDULLAS3','BASTILASHANDARK',
    'BOSSK','FIRSTORDEREXECUTIONER','VADER','COUNTDOOKU','MISSIONVAO',    'GEONOSIANBROODALPHA','MAUL','JOLEEBINDO',
    'CHIEFNEBIT','TUSKENSHAMAN','IMPERIALSUPERCOMMANDO','FIRSTORDERTIEPILOT','DARTHSION',    'FIRSTORDERTROOPER',
    'GREEDO','HOTHLEIA','CHEWBACCALEGENDARY','CHOPPERS3','BOBAFETT','WATTAMBOR','WEDGEANTILLES','DEATHTROOPER',
    'CARTHONASI','ARCTROOPER501ST','WICKET','MACEWINDU','DATHCHA','JYNERSO','TEEBO','AMILYNHOLDO','URORRURRR',
    'SITHASSASSIN', 'SNOWTROOPER',    'SHORETROOPER', 'PRINCESSLEIA', 'SAVAGEOPRESS','DARTHMALAK', 'FINN',
    'PHASMA', 'EZRABRIDGERS3', 'FIRSTORDEROFFICERMALE', 'RESISTANCEPILOT',    'KUIIL', 'AURRA_SING',
    'JEDIKNIGHTGUARDIAN', 'CANDEROUSORDO', 'CADBANE', 'TIEFIGHTERPILOT', 'GRANDMASTERYODA', 'SHAAKTI', 'BISTAN', 'IG11'
]

dict_cPIT_botTeams = [
    {
        'team': 'PADME',
        'teamMember':
        [
            {'tm1': 'PADMEAMIDALA', 'tm2': 'AHSOKATANO', 'tm3': 'ANAKINKNIGHT', 'tm4': 'GENERALKENOBI', 'tm5': 'C3POLEGENDARY'}
        ],
        'averageDamagePerPhase':
        [
            {'p1': 4.5, 'p2': 4.5, 'p3': 4.5, 'p4': 4.5}
        ],
    },
    {
        'team': 'GENERALSKYWALKER',
        'teamMember': [
            {'tm1': 'GENERALSKYWALKER', 'tm2': 'CT7567', 'tm3': 'ARCTROOPER501ST', 'tm4': 'CT210408', 'tm5': 'CT5555'}
        ],
        'averageDamagePerPhase':
        [
            {'p1': 4, 'p2': 4, 'p3': 4, 'p4': 4}
        ],
    }
]

# 'averageDamagePerPhase':
# [
#     {'p1': 3},
#     {'p2': 3},
#     {'p3': 3},
#     {'p4': 3},
# ],
# 'maxDamagePerPhase':
# [
#     {'p1': 6},
#     {'p2': 6},
#     {'p3': 6},
#     {'p4': 6},
# ]
