
# listAllToons = [
# 'Magmatrooper',
# 'Hermit Yoda',
# 'Greef Karga',
# 'Garazeb "Zeb" Orrelios',
# 'Barriss Offee',
# 'B1 Battle Droid',
# 'CT-21-0408 "Echo"',
# 'BB-8',
# 'Poggle the Lesser',
# 'General Kenobi',
# 'Jawa Scavenger',
# 'L3-37',
# 'Droideka',
# 'Ewok Scout',
# 'K-2SO',
# 'Sith Empire Trooper',
# 'IG-86 Sentinel Droid',
# 'Sith Marauder',
# 'Rey (Jedi Training)',
# 'Threepio & Chewie',
# 'Kylo Ren',
# 'Dengar',
# 'IG-100 MagnaGuard',
# 'Range Trooper',
# 'Qui-Gon Jinn',
# 'Royal Guard',
# 'Geonosian Spy',
# 'Bastila Shan',
# 'Jawa',
# "Qi'ra",
# 'Poe Dameron',
# 'Talia',
# 'Nightsister Zombie',
# 'Scarif Rebel Pathfinder',
# 'Grand Admiral Thrawn',
# 'Imperial Probe Droid',
# 'Sabine Wren',
# 'Young Han Solo',
# 'Paploo',
# 'Ewok Elder',
# 'Resistance Hero Poe',
# 'Chief Chirpa',
# 'General Hux',
# 'Visas Marr',
# 'CT-5555 "Fives"',
# 'Luke Skywalker (Farmboy)',
# 'Lando Calrissian',
# 'Jedi Knight Anakin',
# 'Admiral Piett',
# 'Nightsister Spirit',
# 'Clone Sergeant - Phase I',
# 'Admiral Ackbar',
# 'Ahsoka Tano (Fulcrum)',
# 'Stormtrooper',
# 'Luminara Unduli',
# 'Jango Fett',
# 'Hoth Rebel Scout',
# 'Nute Gunray',
# 'General Veers',
# 'Pao',
# 'IG-88',
# 'Rey (Scavenger)',
# 'Darth Nihilus',
# 'Emperor Palpatine',
# 'Mon Mothma',
# 'Captain Han Solo',
# 'Plo Koon',
# 'Old Daka',
# 'Grand Moff Tarkin',
# 'Logray',
# 'Geonosian Soldier',
# 'Cara Dune',
# 'Resistance Trooper',
# 'HK-47',
# 'Tusken Raider',
# 'Cassian Andor',
# 'Darth Traya',
# 'Resistance Hero Finn',
# 'Zaalbar',
# 'Clone Wars Chewbacca',
# 'Commander Luke Skywalker',
# 'B2 Super Battle Droid',
# 'Darth Sidious',
# 'Obi-Wan Kenobi (Old Ben)',
# 'Kylo Ren (Unmasked)',
# 'Vandor Chewbacca',
# 'Young Lando Calrissian',
# 'Han Solo',
# 'Veteran Smuggler Han Solo',
# 'The Mandalorian',
# 'Ugnaught',
# 'Sith Trooper',
# 'Wampa',
# 'Veteran Smuggler Chewbacca',
# 'Darth Revan',
# 'R2-D2',
# 'Mob Enforcer',
# 'Gar Saxon',
# 'Coruscant Underworld Police',
# 'Enfys Nest',
# 'Mother Talzin',
# 'Biggs Darklighter',
# 'CC-2224 "Cody"',
# 'C-3PO',
# 'Jedi Knight Revan',
# 'Padmé Amidala',
# 'Nightsister Initiate',
# 'CT-7567 "Rex"',
# 'Moff Gideon',
# 'Jawa Engineer',
# 'Zam Wesell',
# 'Jedi Knight Luke Skywalker',
# 'Sun Fac',
# 'Lobot',
# 'Embo',
# 'Ima-Gun Di',
# 'Eeth Koth',
# 'T3-M4',
# 'Hoth Rebel Soldier',
# 'Asajj Ventress',
# 'General Grievous',
# 'Chirrut Îmwe',
# 'Juhani',
# 'Kanan Jarrus',
# 'Rose Tico',
# 'Jedi Consular',
# 'Ahsoka Tano',
# 'Director Krennic',
# 'Stormtrooper Han',
# 'Hera Syndulla',
# 'Bastila Shan (Fallen)',
# 'Bossk',
# 'First Order Executioner',
# 'Darth Vader',
# 'Count Dooku',
# 'Mission Vao',
# 'Darth Maul',
# 'Jolee Bindo',
# 'Chief Nebit',
# 'Tusken Shaman',
# 'Imperial Super Commando',
# 'First Order TIE Pilot',
# 'Darth Sion',
# 'First Order Stormtrooper',
# 'Greedo',
# 'Rebel Officer Leia Organa',
# 'Bodhi Rook',
# 'Chewbacca',
# 'Chopper',
# 'Boba Fett',
# 'Wat Tambor',
# 'Wedge Antilles',
# 'Carth Onasi',
# 'Death Trooper',
# 'Wicket',
# 'Mace Windu',
# 'Dathcha',
# 'Teebo',
# 'Rey',
# 'Amilyn Holdo',
# 'Sith Assassin',
# 'Snowtrooper',
# 'Shoretrooper',
# 'Princess Leia',
# 'Savage Opress',
# 'Finn',
# 'Captain Phasma',
# 'Ezra Bridger',
# 'First Order Officer',
# 'Aayla Secura',
# 'Resistance Pilot',
# 'Aurra Sing',
# 'Jedi Knight Guardian',
# 'Canderous Ordo',
# 'Cad Bane',
# 'TIE Fighter Pilot',
# 'Grand Master Yoda',
# 'Shaak Ti',
# 'Bistan'
# ]

listAllToons = [
    'Magmatrooper',
    'Hermit Yoda',
    'Greef Karga',
    'Garazeb "Zeb" Orrelios',
    'Barriss Offee',
    'B1 Battle Droid',
    'CT-21-0408 "Echo"',
    'BB-8',
    'Poggle the Lesser',
    'General Kenobi',
    'Jawa Scavenger',
    'L3-37',
    'Droideka',
    'Ewok Scout',
    'K-2SO',
    'Sith Empire Trooper',
    'IG-86 Sentinel Droid',
    'Sith Marauder',
    'Rey (Jedi Training)',
    'Threepio & Chewie',
    'Kylo Ren',
    'Dengar',
    'IG-100 MagnaGuard',
    'Range Trooper',
    'Qui-Gon Jinn',
    'Royal Guard',
    'Geonosian Spy',
    'Bastila Shan',
    'Jawa',
    "Qi'ra",
    'Poe Dameron',
    'Talia',
    'Nightsister Zombie',
    'Scarif Rebel Pathfinder',
    'Grand Admiral Thrawn',
    'Imperial Probe Droid',
    'Sabine Wren',
    'Young Han Solo',
    'Paploo',
    'Ewok Elder',
    'Resistance Hero Poe',
    'Chief Chirpa',
    'General Hux',
    'Visas Marr',
    'CT-5555 "Fives"',
    'Luke Skywalker (Farmboy)',
    'Lando Calrissian',
    'Jedi Knight Anakin',
    'Admiral Piett',
    'Nightsister Spirit',
    'Clone Sergeant - Phase I',
    'Admiral Ackbar',
    'Ahsoka Tano (Fulcrum)',
    'Stormtrooper',
    'Luminara Unduli',
    'Jango Fett',
    'Hoth Rebel Scout',
    'Nute Gunray',
    'General Veers',
    'Pao',
    'IG-88',
    'Rey (Scavenger)',
    'Darth Nihilus',
    'Emperor Palpatine',
    'Mon Mothma',
    'Captain Han Solo',
    'Plo Koon',
    'Old Daka',
    'Grand Moff Tarkin',
    'Logray',
    'Geonosian Soldier',
    'Cara Dune',
    'Resistance Trooper',
    'HK-47',
    'Tusken Raider',
    'Cassian Andor',
    'Darth Traya',
    'Resistance Hero Finn',
    'Zaalbar',
    'Clone Wars Chewbacca',
    'Commander Luke Skywalker',
    'B2 Super Battle Droid',
    'Darth Sidious',
    'Obi-Wan Kenobi (Old Ben)',
    'Kylo Ren (Unmasked)',
    'Vandor Chewbacca',
    'Young Lando Calrissian',
    'Han Solo',
    'Veteran Smuggler Han Solo',
    'The Mandalorian',
    'Ugnaught',
    'Sith Trooper',
    'Wampa',
    'Veteran Smuggler Chewbacca',
    'Darth Revan',
    'R2-D2',
    'Mob Enforcer',
    'Gar Saxon',
    'Coruscant Underworld Police',
    'Enfys Nest',
    'Mother Talzin',
    'Biggs Darklighter',
    'CC-2224 "Cody"',
    'C-3PO',
    'Jedi Knight Revan',
    'Padmé Amidala',
    'Nightsister Initiate',
    'CT-7567 "Rex"',
    'Moff Gideon',
    'Jawa Engineer',
    'Zam Wesell',
    'Jedi Knight Luke Skywalker',
    'Sun Fac',
    'Lobot',
    'Embo',
    'Ima-Gun Di',
    'Eeth Koth',
    'T3-M4',
    'Hoth Rebel Soldier',
    'Asajj Ventress',
    'General Grievous',
    'Chirrut ÃŽmwe',
    'Juhani',
    'Kanan Jarrus',
    'Rose Tico',
    'Jedi Consular',
    'Ahsoka Tano',
    'Director Krennic',
    'Stormtrooper Han',
    'Hera Syndulla',
    'Bastila Shan (Fallen)',
    'Bossk',
    'First Order Executioner',
    'Darth Vader',
    'Count Dooku',
    'Mission Vao',
    'Darth Maul',
    'Jolee Bindo',
    'Chief Nebit',
    'Tusken Shaman',
    'Imperial Super Commando',
    'First Order TIE Pilot',
    'Darth Sion',
    'First Order Stormtrooper',
    'Greedo',
    'Rebel Officer Leia Organa',
    'Bodhi Rook',
    'Chewbacca',
    'Chopper',
    'Boba Fett',
    'Wat Tambor',
    'Wedge Antilles',
    'Carth Onasi',
    'Death Trooper',
    'Wicket',
    'Mace Windu',
    'Dathcha',
    'Teebo',
    'Rey',
    'Amilyn Holdo',
    'Sith Assassin',
    'Snowtrooper',
    'Shoretrooper',
    'Princess Leia',
    'Savage Opress',
    'Finn',
    'Captain Phasma',
    'Ezra Bridger',
    'First Order Officer',
    'Aayla Secura',
    'Resistance Pilot',
    'Aurra Sing',
    'Jedi Knight Guardian',
    'Canderous Ordo',
    'Cad Bane',
    'TIE Fighter Pilot',
    'Grand Master Yoda',
    'Shaak Ti',
    'Bistan',
    'Colonel Starck',
    'First Order SF TIE Pilot',
    'Nightsister Acolyte',
    'Jedi Master Luke Skywalker',
    'Kit Fisto',
    'General Skywalker',
    'Supreme Leader Kylo Ren',
    'Baze Malbus',
    'The Armorer',
    'The Mandalorian (Beskar Armor)',
    'Geonosian Brood Alpha',
    'ARC Trooper',
    'Jyn Erso',
    'URoRRuR'R'R',
    'Darth Malak',
    'Kuiil',
    'IG-11',
    'Gamorrean Guard',
    'Sith Eternal Emperor'
]

list_gls = [
'Jedi Master Luke Skywalker',
'Rey',
'Supreme Leader Kylo Ren',
'Sith Eternal Emperor'
]

list_criticalToons = [
'Darth Malak',
'Darth Revan',
'Bastila Shan (Fallen)',
'Jedi Knight Revan',
'Padmé Amidala',
'General Skywalker',
'General Grievous',
'Enfys Nest',
'Commander Luke Skywalker',
'Wat Tambor',
'Darth Traya',
'Geonosian Brood Alpha',
'Negotiator',
'Malevolence'
]

dict_cPIT_botTeams = [
    {
        'team': 'PADME',
        'teamMember':
        [
            {'tm1': 'PADMEAMIDALA', 'tm2': 'AHSOKATANO', 'tm3': 'ANAKINKNIGHT', 'tm4': 'GENERALKENOBI', 'tm5': 'C3POLEGENDARY'}
        ],
        'averageDamagePerPhase':
        [
            {'p1': 4.5, 'p2': 4.5, 'p3': 4.5, 'p4': 4.5}
        ],
    },
    {
        'team': 'GENERALSKYWALKER',
        'teamMember': [
            {'tm1': 'GENERALSKYWALKER', 'tm2': 'CT7567', 'tm3': 'ARCTROOPER501ST', 'tm4': 'CT210408', 'tm5': 'CT5555'}
        ],
        'averageDamagePerPhase':
        [
            {'p1': 4, 'p2': 4, 'p3': 4, 'p4': 4}
        ],
    }
]

# 'averageDamagePerPhase':
# [
#     {'p1': 3},
#     {'p2': 3},
#     {'p3': 3},
#     {'p4': 3},
# ],
# 'maxDamagePerPhase':
# [
#     {'p1': 6},
#     {'p2': 6},
#     {'p3': 6},
#     {'p4': 6},
# ]
